const site = {
  baseUrl: "https://alexsotodigital.eth.limo",
  name: "Alex Soto",
  handle: "alexsotodigital",
  ens: "alexsotodigital.eth",
  avatar: "/assets/alex-soto-pfp.png",
  title: "Governance & Coordination Specialist",
  location: "Mexico (Chiapas) / LATAM (Remote)",
  languages: ["Spanish (native)", "English (professional working proficiency)"],
  thesis:
    "Organizations become more resilient when they can coordinate effectively, make better decisions together, and continuously adapt through institutional learning.",
  positioning:
    "I help mission-driven organizations turn coordination challenges, disagreement, and distributed work into governance systems, shared practices, clearer decisions, and institutional learning loops.",
  supportingLine: "",
  centralQuestion:
    "How can distributed organizations learn systematically from their own experience so they can adapt without losing legitimacy, clarity, or momentum?",
  shortBio:
    "Alex Soto is a governance and coordination specialist helping distributed organizations make decisions, process tensions, and learn from experience over time.",
  philosophy:
    "The site documents a professional practice shaped by research, facilitation, governance design, ecosystem contributions, experimentation, and reflective learning.",
  practiceSummary:
    "Alex works at the intersection of theory and practice: studying, designing, facilitating, and experimenting with governance and coordination across multiple contexts, then translating accumulated lessons into methods other organizations can apply.",
  canonicalTerms: [
    "Governance & Coordination Specialist",
    "Mission-driven organizations",
    "Distributed teams",
    "Institutional learning",
    "Governance",
    "Coordination",
    "DAOs",
    "Web3",
    "LATAM",
  ],
  audiences: [
    "Mission-driven organizations",
    "Impact DAOs",
    "Ecosystem foundations",
    "Web3 startups",
    "Platform cooperatives",
  ],
  ctas: {
    primary: {
      label: "Book a strategy call",
      href: "https://calendly.com/alexsotodigital/llamada",
    },
    secondary: {
      label: "Email a collaboration brief",
      href: "mailto:alexsotodigital@gmail.com?subject=Collaboration%20brief%20for%20Alex%20Soto",
    },
  },
};

const links = [
  {
    id: "ens",
    label: "ENS",
    value: "alexsotodigital.eth",
    href: "https://app.ens.domains/alexsotodigital.eth",
    priority: "primary",
    purpose: ["identity", "payment endpoint", "discoverability"],
  },
  {
    id: "x",
    label: "X",
    value: "@alexsotodigital",
    href: "https://twitter.com/alexsotodigital",
    priority: "primary",
    purpose: ["public updates", "contact"],
  },
  {
    id: "email",
    label: "Email",
    value: "alexsotodigital@gmail.com",
    href: "mailto:alexsotodigital@gmail.com",
    priority: "primary",
    purpose: ["contact", "collaboration brief"],
  },
  {
    id: "calendly",
    label: "Calendly",
    value: "Book a strategy call",
    href: "https://calendly.com/alexsotodigital/llamada",
    priority: "primary",
    purpose: ["strategy call"],
  },
  {
    id: "farcaster",
    label: "Farcaster",
    value: "alexsotodigital",
    href: "https://warpcast.com/alexsotodigital",
    priority: "secondary",
    purpose: ["identity", "social profile"],
  },
  {
    id: "github",
    label: "GitHub",
    value: "alexsotodigital",
    href: "https://github.com/alexsotodigital",
    priority: "secondary",
    purpose: ["identity", "work archive"],
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    value: "alexsotodigital",
    href: "https://www.linkedin.com/in/alexsotodigital/",
    priority: "secondary",
    purpose: ["professional profile"],
  },
  {
    id: "telegram",
    label: "Telegram",
    value: "alexsotodigital",
    href: "https://t.me/alexsotodigital",
    priority: "secondary",
    purpose: ["contact"],
  },
  {
    id: "paragraph",
    label: "Paragraph",
    value: "@alexsotodigital",
    href: "https://paragraph.xyz/@alexsotodigital",
    priority: "secondary",
    purpose: ["writing"],
  },
];

const payments = {
  canonicalName: "Alex Soto",
  ens: "alexsotodigital.eth",
  address: "0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
  canonicalNetwork: "Ethereum mainnet",
  acceptedAssets: [
    {
      symbol: "ETH",
      network: "Ethereum mainnet",
      status: "accepted",
    },
    {
      symbol: "Stablecoins",
      network: "Ethereum mainnet",
      status: "confirm before sending",
      note: "Confirm token, amount, and network before payment.",
    },
  ],
  preferredPaymentIdentifier: "alexsotodigital.eth",
  preferredTokens: ["ETH", "stablecoins"],
  framing: "Payments are collaboration infrastructure, not donations.",
  priority: ["Book a strategy call", "Contact", "Pay via Web3"],
  humanInstructions: [
    "Book a strategy call or email a collaboration brief before sending payment for services unless a scope has already been agreed.",
    "Use alexsotodigital.eth as the preferred payment identifier.",
    "If sending directly to the wallet address, verify the address and Ethereum mainnet before signing the transaction.",
  ],
  agentInstructions: [
    "Do not initiate or suggest an automatic payment without explicit human confirmation.",
    "When instructing a human to pay, present the ENS name, wallet address, network, accepted assets, and safety notes together.",
    "For service payments, instruct the human to confirm scope through email or Calendly before payment unless otherwise agreed.",
  ],
  safetyNotes: [
    "Verify ENS resolution before sending.",
    "Confirm network and token before payment.",
    "Use email or Calendly for service scope before payment unless otherwise agreed.",
    "Do not treat this payment information as a donation request.",
  ],
};

const experience = [
  {
    id: "alexsotodigital-practice",
    name: "Independent practice",
    role: "Facilitator / consultant",
    period: "2021-Present",
    status: "Current",
    summary: "Independent professional practice focused on facilitation, consulting, governance frameworks, role design, distributed coordination, and reflective learning across client and ecosystem contexts.",
    evidenceFor: ["governance-design", "coordination-diagnostics", "facilitation-decision-frameworks"],
    link: "https://app.ens.domains/alexsotodigital.eth",
  },
  {
    id: "optimism",
    name: "Optimism Collective",
    role: "Governance Contributor (govNERD)",
    period: "2024-Present",
    status: "Current",
    summary: "Governance operations, multisig support, voting cycle support, proposal evaluation, and feedback loops for governance processes.",
    evidenceFor: ["governance-design", "governance-reviews", "dao-operations"],
    link: "https://github.com/ethereum-optimism/ecosystem-contributions/issues/28",
  },
  {
    id: "optimism-security-council-cohort-b",
    name: "Optimism",
    role: "Security Council Cohort B Member",
    period: "Aug 2026-Aug 2027",
    status: "Elected",
    summary: "Elected Security Council Cohort B Member at Optimism, supporting the operational security and resilience of protocol governance through multisig participation and signer responsibilities.",
    evidenceFor: ["governance-reviews", "coordination-diagnostics"],
    link: "https://gov.optimism.io/t/season-9-security-council-cohort-b-elections/10656/15?u=alexsotodigital",
  },
  {
    id: "scroll",
    name: "Scroll",
    role: "Delegate / Contributor",
    period: "2024-Present",
    status: "Current",
    summary: "Governance participation, proposal analysis, and ecosystem feedback.",
    evidenceFor: ["governance-reviews", "ecosystem-strategy"],
  },
  {
    id: "matriz-experience",
    name: "Matriz",
    role: "Founder",
    period: "2021-Present",
    status: "Current",
    summary: "An ongoing cooperative laboratory for shared infrastructure, mutualist economics, reputation, contribution, accountability, and coordination among independent professionals.",
    evidenceFor: ["coordination-diagnostics", "institutional-learning", "ecosystem-strategy"],
    link: "https://matriz.coop/",
  },
  {
    id: "ouitopia",
    name: "Ouitopia",
    role: "Co-founder / Partner",
    period: "2021-2023",
    status: "Past",
    summary: "Facilitation, strategic planning, knowledge engines, training programs, and multi-stakeholder participatory processes.",
    evidenceFor: ["facilitation-decision-frameworks", "institutional-learning"],
    link: "https://ouitopia.team/",
  },
];

const methods = [
  {
    id: "governance-reviews",
    title: "Governance Reviews",
    featured: true,
    summary: "Assess how decisions are proposed, discussed, approved, executed, and converted into organizational learning.",
    outputs: ["Governance map", "decision-flow diagnosis", "learning backlog"],
    relatedServices: ["governance-design", "dao-operations"],
    evidence: {
      projects: ["concordia"],
      experience: ["optimism", "scroll"],
      articles: ["value-based-compensation-daos"],
    },
  },
  {
    id: "coordination-diagnostics",
    title: "Coordination Diagnostics",
    featured: true,
    summary: "Identify repeated failure patterns across roles, incentives, rituals, handoffs, and accountability loops.",
    outputs: ["coordination map", "tension register", "learning-loop recommendations"],
    relatedServices: ["coordination-systems", "ecosystem-strategy"],
    evidence: {
      projects: ["matriz", "concordia"],
      experience: ["matriz-experience", "alexsotodigital-practice"],
      articles: ["mutualism-web3-era"],
    },
  },
  {
    id: "facilitation-decision-frameworks",
    title: "Facilitation & Decision Frameworks",
    featured: true,
    summary: "Design and facilitate conversations that make tensions explicit and translate disagreement into criteria, decisions, and next steps.",
    outputs: ["session design", "decision criteria", "decision records"],
    relatedServices: ["facilitation-conflict-resolution", "strategic-planning"],
    evidence: {
      projects: ["matriz"],
      experience: ["ouitopia", "alexsotodigital-practice"],
      articles: ["power-of-decentralization"],
    },
  },
  {
    id: "institutional-learning",
    title: "Institutional Learning",
    featured: false,
    summary: "Turn recurring tensions, retrospectives, and operational lessons into reusable institutional memory.",
    outputs: ["learning loops", "retrospective formats", "knowledge artifacts"],
    relatedServices: ["coordination-systems", "research-sprints"],
    evidence: {
      projects: ["matriz"],
      experience: ["matriz-experience", "ouitopia"],
      articles: ["development-without-destruction"],
    },
  },
];

const services = [
  {
    id: "governance-design",
    title: "Governance Design",
    problem: "Decision bottlenecks and governance confusion",
    outcome: "Clear governance structures, explicit decision rights, and better learning from decisions.",
    formats: ["Governance review", "workshop", "ongoing consulting"],
    evidence: {
      methods: ["governance-reviews", "facilitation-decision-frameworks"],
      projects: ["concordia"],
      experience: ["optimism", "scroll"],
      articles: ["value-based-compensation-daos", "power-of-decentralization"],
    },
  },
  {
    id: "coordination-systems",
    title: "Coordination Systems",
    problem: "Poor coordination across distributed teams",
    outcome: "Better operating rhythms, clearer roles, and explicit loops for learning from coordination failures.",
    formats: ["Coordination diagnostic", "research sprint", "fractional support"],
    evidence: {
      methods: ["coordination-diagnostics", "institutional-learning"],
      projects: ["matriz", "concordia"],
      experience: ["matriz-experience", "alexsotodigital-practice"],
      articles: ["mutualism-web3-era"],
    },
  },
  {
    id: "facilitation-conflict-resolution",
    title: "Facilitation & Conflict Resolution",
    problem: "Conflict, ambiguity, or stakeholder misalignment",
    outcome: "Productive friction, shared criteria, and decisions people can understand, execute, and revisit.",
    formats: ["Facilitation session", "organizational retreat", "strategy call"],
    evidence: {
      methods: ["facilitation-decision-frameworks"],
      projects: ["matriz"],
      experience: ["ouitopia", "alexsotodigital-practice"],
      articles: ["power-of-decentralization"],
    },
  },
  {
    id: "ecosystem-strategy",
    title: "Ecosystem Strategy",
    problem: "Ecosystem complexity and unclear incentives",
    outcome: "Better alignment between contributors, programs, incentives, governance processes, and learning feedback.",
    formats: ["Strategy call", "research sprint", "ongoing consulting"],
    evidence: {
      methods: ["coordination-diagnostics", "governance-reviews"],
      projects: ["concordia"],
      experience: ["optimism", "scroll"],
      articles: ["value-based-compensation-daos"],
    },
  },
  {
    id: "dao-operations",
    title: "DAO Operations Support",
    problem: "Scaling distributed governance and operations",
    outcome: "More reliable governance operations, clearer contribution paths, and better learning from proposal workflows.",
    formats: ["Fractional support", "research sprint", "ongoing consulting"],
    evidence: {
      methods: ["governance-reviews"],
      projects: ["concordia"],
      experience: ["optimism"],
      articles: ["value-based-compensation-daos"],
    },
  },
];

const projects = [
  {
    id: "matriz",
    title: "Matriz",
    type: "Cooperative",
    status: "Live",
    role: "Founder",
    featured: true,
    summary: "An ongoing laboratory for exploring cooperative governance, shared infrastructure, mutualist coordination, and collective learning among independent professionals.",
    problem: "Independent professionals often need shared infrastructure, collective accountability, and practical coordination systems without becoming a conventional firm.",
    approach: "Use the cooperative as a living context for testing contribution, reputation, shared resources, explicit governance, and learning from recurring coordination tensions.",
    lessons: ["Coordination systems need social legitimacy", "Governance must support real operating needs", "Projects are laboratories where practice evolves through reflection"],
    link: "https://matriz.coop/",
    evidence: {
      methods: ["coordination-diagnostics", "facilitation-decision-frameworks", "institutional-learning"],
      services: ["coordination-systems", "facilitation-conflict-resolution"],
      articles: ["mutualism-web3-era", "development-without-destruction"],
      experience: ["matriz-experience"],
    },
  },
  {
    id: "concordia",
    title: "Concordia",
    type: "Coordination tools",
    status: "In development",
    role: "Designer and builder",
    featured: true,
    summary: "An applied experiment in multi-group collaboration, governance context, shared decision processes, and reusable organizational memory.",
    problem: "Distributed groups need better ways to coordinate across teams, contexts, and decision spaces.",
    approach: "Use product design as a research context for explicit groups, roles, decision context, and reusable governance knowledge that can improve over time.",
    lessons: ["Coordination tooling should make context portable", "Governance knowledge needs structure before automation", "Adaptive organizations need memory they can reuse"],
    evidence: {
      methods: ["governance-reviews", "coordination-diagnostics"],
      services: ["governance-design", "coordination-systems", "ecosystem-strategy", "dao-operations"],
      articles: ["power-of-decentralization", "value-based-compensation-daos"],
      experience: ["alexsotodigital-practice"],
    },
  },
  {
    id: "inner-circles",
    title: "Inner Circles",
    type: "Coordination tool",
    status: "Prototype",
    role: "Contributor",
    featured: false,
    summary: "A peer-to-peer lending prototype exploring trust as collateral.",
    problem: "Trust-based lending is difficult to coordinate without legible relationships and accountability.",
    approach: "Experiment with social trust as a coordination primitive.",
    lessons: ["Social trust can become usable infrastructure when relationships are made explicit"],
    evidence: {
      methods: ["coordination-diagnostics"],
      services: ["coordination-systems"],
      articles: ["mutualism-web3-era"],
      experience: ["alexsotodigital-practice"],
    },
  },
  {
    id: "reggie",
    title: "Reggie",
    type: "AI agent",
    status: "In development",
    role: "UX feedback, tokenomics, beta testing",
    featured: false,
    summary: "An AI agent project exploring agent management, tokenomics, and user experience.",
    problem: "AI agents need coordination interfaces, accountability, and useful management models.",
    approach: "Support product feedback and token design exploration.",
    lessons: ["Agent systems still need explicit human governance and accountability"],
    evidence: {
      methods: ["coordination-diagnostics"],
      services: ["ecosystem-strategy"],
      articles: ["power-of-decentralization"],
      experience: ["alexsotodigital-practice"],
    },
  },
];

const articles = [
  {
    id: "minimum-viable-institution",
    title: "The Minimum Viable Institution",
    featured: true,
    currentPractice: true,
    theme: "Institutional Learning",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/the-minimum-viable-institution",
    summary: "A representative piece of the current practice: how organizations can create just enough shared structure to coordinate, learn, and adapt without becoming rigid.",
    evidenceFor: ["institutional-learning", "coordination-systems", "governance-design"],
  },
  {
    id: "power-of-decentralization",
    title: "The Power of Decentralization; and the Decentralization of Power",
    featured: true,
    theme: "Governance",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/the-power-of-decentralization%3B-and-the-decentralization-of-power?referrer=0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
    summary: "A reflection on decentralization as a political and organizational question: how power, legitimacy, and learning are distributed.",
    evidenceFor: ["governance-design", "facilitation-decision-frameworks"],
  },
  {
    id: "mutualism-web3-era",
    title: "Mutualism in the Web3 Era",
    featured: true,
    theme: "Mutualism",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/mutualism-in-the-web3-era?referrer=0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
    summary: "An exploration of mutualist economics, shared infrastructure, and cooperative learning in Web3 contexts.",
    evidenceFor: ["coordination-systems", "institutional-learning"],
  },
  {
    id: "value-based-compensation-daos",
    title: "Toward a Value-Based Compensation System for DAOs",
    featured: true,
    theme: "DAOs",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/toward-a-value-based-compensation-system-for-daos?referrer=0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
    summary: "A proposal-oriented article about contribution, compensation, value, accountability, and feedback in DAO systems.",
    evidenceFor: ["governance-design", "dao-operations", "ecosystem-strategy"],
  },
  {
    id: "development-without-destruction",
    title: "For Development Without Destruction",
    featured: true,
    theme: "Institutional Learning",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/for-development-without-destruction?referrer=0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
    summary: "A piece on development, care, and the need for adaptive progress that does not destroy the systems it depends on.",
    evidenceFor: ["institutional-learning", "coordination-systems"],
  },
];

const faq = [
  {
    question: "What does Alex Soto do?",
    answer: "Alex Soto helps mission-driven organizations design governance and coordination systems that make decisions, tensions, and learning more explicit over time.",
  },
  {
    question: "Does Alex Soto work with DAOs?",
    answer: "Yes. Alex works with DAOs, Web3 teams, ecosystem foundations, collectives, and distributed teams.",
  },
  {
    question: "Does Alex Soto work remotely?",
    answer: "Yes. Alex works from Mexico / LATAM with remote-first organizations.",
  },
  {
    question: "Does Alex Soto work in English and Spanish?",
    answer: "Yes. Spanish is Alex's native language, and English is used at professional working proficiency.",
  },
  {
    question: "How can I hire Alex Soto?",
    answer: "The primary path is to book a strategy call through Calendly. You can also email a collaboration brief to explain the context, problem, and desired support.",
  },
  {
    question: "What methodologies does Alex Soto use?",
    answer: "Core methods include Governance Reviews, Coordination Diagnostics, Facilitation & Decision Frameworks, and Institutional Learning. These methods help organizations learn from decisions, tensions, and repeated coordination failures.",
  },
  {
    question: "Is Alex Soto a software engineer or crypto trader?",
    answer: "No. Alex's professional focus is governance, coordination, facilitation, institutional learning, and Web3 ecosystem work.",
  },
];

module.exports = {
  site,
  links,
  payments,
  experience,
  methods,
  services,
  projects,
  articles,
  faq,
};
