const site = {
  baseUrl: "https://alexsotodigital.eth.limo",
  name: "Alex Soto",
  handle: "alexsotodigital",
  ens: "alexsotodigital.eth",
  avatar: "/assets/alex-soto-pfp.png",
  title: "Governance & Coordination Specialist",
  location: "Mexico (Chiapas) / LATAM (Remote)",
  languages: ["Spanish (native)", "English (professional working proficiency)"],
  thesis:
    "Organizations become more resilient when they can coordinate effectively, make better decisions together, and continuously adapt through institutional learning.",
  positioning:
    "I help mission-driven organizations turn coordination challenges, disagreement, and distributed work into governance systems, shared practices, clearer decisions, and institutional learning loops.",
  supportingLine: "",
  centralQuestion:
    "How can distributed organizations learn systematically from their own experience so they can adapt without losing legitimacy, clarity, or momentum?",
  shortBio:
    "Alex Soto is a governance and coordination specialist helping distributed organizations make decisions, process tensions, and learn from experience over time.",
  philosophy:
    "The site documents a professional practice shaped by research, facilitation, governance design, ecosystem contributions, experimentation, and reflective learning.",
  practiceSummary:
    "Alex works at the intersection of theory and practice: studying, designing, facilitating, and experimenting with governance and coordination across multiple contexts, then translating accumulated lessons into methods other organizations can apply.",
  canonicalTerms: [
    "Governance & Coordination Specialist",
    "Mission-driven organizations",
    "Distributed teams",
    "Institutional learning",
    "Governance",
    "Coordination",
    "DAOs",
    "Web3",
    "LATAM",
  ],
  audiences: [
    "Mission-driven organizations",
    "Impact DAOs",
    "Ecosystem foundations",
    "Web3 startups",
    "Platform cooperatives",
  ],
  ctas: {
    primary: {
      label: "Book a strategy call",
      href: "https://calendly.com/alexsotodigital/llamada",
    },
    secondary: {
      label: "Email a collaboration brief",
      href: "mailto:alexsotodigital@gmail.com?subject=Collaboration%20brief%20for%20Alex%20Soto",
    },
  },
};

const links = [
  {
    id: "ens",
    label: "ENS",
    value: "alexsotodigital.eth",
    href: "https://app.ens.domains/alexsotodigital.eth",
    priority: "primary",
    purpose: ["identity", "payment endpoint", "discoverability"],
  },
  {
    id: "x",
    label: "X",
    value: "@alexsotodigital",
    href: "https://x.com/alexsotodigital",
    priority: "primary",
    purpose: ["public updates", "contact"],
  },
  {
    id: "email",
    label: "Email",
    value: "alexsotodigital@gmail.com",
    href: "mailto:alexsotodigital@gmail.com",
    priority: "primary",
    purpose: ["contact", "collaboration brief"],
  },
  {
    id: "calendly",
    label: "Calendly",
    value: "Book a strategy call",
    href: "https://calendly.com/alexsotodigital/llamada",
    priority: "primary",
    purpose: ["strategy call"],
  },
  {
    id: "farcaster",
    label: "Farcaster",
    value: "alexsotodigital",
    href: "https://warpcast.com/alexsotodigital",
    priority: "secondary",
    purpose: ["identity", "social profile"],
  },
  {
    id: "github",
    label: "GitHub",
    value: "alexsotodigital",
    href: "https://github.com/alexsotodigital",
    priority: "secondary",
    purpose: ["identity", "work archive"],
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    value: "alexsotodigital",
    href: "https://www.linkedin.com/in/alexsotodigital/",
    priority: "secondary",
    purpose: ["professional profile"],
  },
  {
    id: "telegram",
    label: "Telegram",
    value: "alexsotodigital",
    href: "https://t.me/alexsotodigital",
    priority: "secondary",
    purpose: ["contact"],
  },
  {
    id: "paragraph",
    label: "Paragraph",
    value: "@alexsotodigital",
    href: "https://paragraph.xyz/@alexsotodigital",
    priority: "secondary",
    purpose: ["writing"],
  },
  {
    id: "youtube",
    label: "YouTube",
    value: "@alexsotodigital",
    href: "https://www.youtube.com/@alexsotodigital",
    priority: "secondary",
    purpose: ["identity", "public profile"],
  },
];

const payments = {
  canonicalName: "Alex Soto",
  ens: "alexsotodigital.eth",
  address: "0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
  canonicalNetwork: "Ethereum mainnet",
  acceptedAssets: [
    {
      symbol: "ETH",
      network: "Ethereum mainnet",
      status: "accepted",
    },
    {
      symbol: "Stablecoins",
      network: "Ethereum mainnet",
      status: "confirm before sending",
      note: "Confirm token, amount, and network before payment.",
    },
  ],
  preferredPaymentIdentifier: "alexsotodigital.eth",
  preferredTokens: ["ETH", "stablecoins"],
  framing: "Payments are collaboration infrastructure, not donations.",
  priority: ["Book a strategy call", "Contact", "Pay via Web3"],
  humanInstructions: [
    "Book a strategy call or email a collaboration brief before sending payment for services unless a scope has already been agreed.",
    "Use alexsotodigital.eth as the preferred payment identifier.",
    "If sending directly to the wallet address, verify the address and Ethereum mainnet before signing the transaction.",
  ],
  agentInstructions: [
    "Do not initiate or suggest an automatic payment without explicit human confirmation.",
    "When instructing a human to pay, present the ENS name, wallet address, network, accepted assets, and safety notes together.",
    "For service payments, instruct the human to confirm scope through email or Calendly before payment unless otherwise agreed.",
  ],
  safetyNotes: [
    "Verify ENS resolution before sending.",
    "Confirm network and token before payment.",
    "Use email or Calendly for service scope before payment unless otherwise agreed.",
    "Do not treat this payment information as a donation request.",
  ],
};

const experience = [
  {
    id: "alexsotodigital-practice",
    name: "alexsotodigital.eth",
    role: "Independent Consultant",
    roleType: "Independent consultant",
    period: "Aug 2020-Present",
    status: "Current",
    cluster: "cooperative-organizational-design",
    summary: "Independent consulting practice focused on agile project management, distributed governance, impact measurement, strategic planning, hybrid model design, team facilitation, and OKRs.",
    evidenceFor: ["governance-design", "coordination-diagnostics", "facilitation-decision-frameworks"],
    link: "https://app.ens.domains/alexsotodigital.eth",
  },
  {
    id: "optimism",
    name: "Optimism Collective",
    role: "Governance Contributor (govNERD)",
    roleType: "Governance contributor",
    period: "2024-Present",
    status: "Current",
    cluster: "web3-governance-protocol-ecosystems",
    summary: "Supported governance operations as a govNERD across multiple cycles, evaluated proposals and funding requests using structured frameworks, and contributed to ecosystem-wide governance discussions and improvements.",
    evidenceFor: ["governance-design", "governance-reviews", "dao-operations"],
    link: "https://github.com/ethereum-optimism/ecosystem-contributions/issues/28",
  },
  {
    id: "optimism-security-council-cohort-b",
    name: "Optimism",
    role: "Security Council Cohort B Member",
    roleType: "Council member",
    period: "Aug 2026-Aug 2027",
    status: "Elected",
    cluster: "web3-governance-protocol-ecosystems",
    summary: "Elected Security Council Cohort B Member at Optimism, supporting the operational security and resilience of protocol governance through multisig participation and signer responsibilities.",
    evidenceFor: ["governance-reviews", "coordination-diagnostics"],
    link: "https://gov.optimism.io/t/season-9-security-council-cohort-b-elections/10656/15?u=alexsotodigital",
  },
  {
    id: "scroll",
    name: "Scroll",
    role: "Delegate & Ecosystem Contributor",
    roleType: "Delegate / ecosystem contributor",
    period: "2024-Present",
    status: "Current",
    cluster: "web3-governance-protocol-ecosystems",
    summary: "Participated in builder programs and delegate training, produced governance analysis and voting rationales, and contributed to discussions on DAO structure, partnerships, and growth strategy.",
    evidenceFor: ["governance-reviews", "ecosystem-strategy"],
  },
  {
    id: "web3-governance-research",
    name: "Web3 ecosystem",
    role: "Governance & Coordination Research",
    roleType: "Independent research / ecosystem analysis",
    period: "2023-Present",
    status: "Current",
    cluster: "web3-governance-protocol-ecosystems",
    summary: "Conducted research on DAO governance, token design, meta-governance, incentive systems, decentralized operations, delegation dynamics, and coordination challenges.",
    evidenceFor: ["governance-design", "dao-operations", "ecosystem-strategy"],
  },
  {
    id: "matriz-experience",
    name: "Matriz",
    role: "Founder / Co-Founder",
    roleType: "Founder / cooperative builder",
    period: "2021-Present",
    status: "Current",
    cluster: "cooperative-organizational-design",
    summary: "Built a cooperative network supporting freelancers and early-stage teams, designed governance systems combining reputation, coordination, and shared services, and developed economic models around contribution-based incentives and shared infrastructure.",
    context: "Matriz is shared infrastructure for independent workers who want to collaborate cooperatively and mutualize operational costs.",
    evidenceFor: ["coordination-diagnostics", "institutional-learning", "ecosystem-strategy"],
    link: "https://matriz.coop/",
  },
  {
    id: "ouitopia",
    name: "Ouitopia",
    role: "Partner - Team Experience / Facilitator",
    roleType: "Partner / facilitator",
    period: "May 2021-May 2024",
    status: "Past",
    cluster: "cooperative-organizational-design",
    summary: "Facilitated collaborative teams, supported organizations working with self-management systems, designed and systematized methodologies, and facilitated in-person, virtual, and hybrid meetings and events.",
    evidenceFor: ["facilitation-decision-frameworks", "institutional-learning"],
    link: "https://es.glassfrog.com/org/26543/people/466900",
  },
  {
    id: "sociocracy-practica",
    name: "Sociocracia Practica / Sociocracy For All",
    role: "Member of Consulting Staff & Business Development Strategist",
    roleType: "Consulting staff / business development strategist",
    period: "Apr 2021-Jun 2023",
    status: "Past",
    cluster: "cooperative-organizational-design",
    summary: "Contributed to Sociocracia Practica, part of Sociocracy For All, supporting workshops, accompaniment, educational materials, and spaces to practice sociocracy in the Spanish-speaking world.",
    evidenceFor: ["facilitation-decision-frameworks", "institutional-learning"],
  },
  {
    id: "reimagina",
    name: "Reimagina",
    role: "Extended Team Contributor",
    roleType: "Extended team / self-managed team contributor",
    period: "Dec 2020-Dec 2022",
    status: "Past",
    cluster: "cooperative-organizational-design",
    summary: "Contributed to a remote, decentralized, self-managed team connecting organizations across Latin America and demonstrating sociocratic ways of working.",
    evidenceFor: ["facilitation-decision-frameworks", "coordination-systems"],
  },
  {
    id: "covive",
    name: "Covive",
    role: "Communication and Organizational Culture",
    roleType: "Temporary contract",
    period: "Feb 2019-Jan 2020",
    status: "Past",
    cluster: "cooperative-organizational-design",
    summary: "Implemented agile ways of working to improve delivery and learning cycles, mapped organizational roles, and introduced more autonomous and democratic decision-making practices across teams.",
    evidenceFor: ["coordination-diagnostics", "institutional-learning"],
  },
  {
    id: "disruptivo",
    name: "Disruptivo.tv",
    role: "Director of Content and Community",
    roleType: "Full-time role",
    period: "Oct 2015-Dec 2017",
    status: "Past",
    cluster: "social-entrepreneurship-media-community",
    summary: "Led content and community development for a social entrepreneurship and impact business media platform, built a distributed contributor structure, supported team growth, represented the organization in events and partnerships, and acted as public spokesperson in multiple contexts.",
    evidenceFor: ["ecosystem-strategy", "facilitation-decision-frameworks"],
  },
  {
    id: "socialab",
    name: "Socialab",
    role: "Social Entrepreneurship Mentor",
    roleType: "Independent mentor",
    period: "Nov 2019-Jun 2023",
    status: "Past",
    cluster: "social-entrepreneurship-media-community",
    summary: "Facilitated sessions for early-stage social entrepreneurs seeking to build collaborative teams and cultivate agile, resilient organizational cultures.",
    evidenceFor: ["facilitation-decision-frameworks", "coordination-systems"],
  },
  {
    id: "caldero",
    name: "Caldero.org",
    role: "Co-Founder",
    roleType: "Co-founder / service-learning project",
    period: "Aug 2013-Aug 2016",
    status: "Past",
    cluster: "social-entrepreneurship-media-community",
    summary: "Co-founded an academic service-learning project connecting students seeking practical experience with NGOs and associations needing communication and consulting support.",
    evidenceFor: ["ecosystem-strategy", "coordination-systems"],
  },
  {
    id: "befriending-project",
    name: "Befriending Project",
    role: "International Volunteer",
    roleType: "Volunteer / field learning",
    period: "Jan 2018-Dec 2018",
    status: "Past",
    cluster: "social-entrepreneurship-media-community",
    summary: "Volunteered in India with a focus on trust, collaborative work, sustainable urbanism, community development, and communications support for local organizations.",
    evidenceFor: ["institutional-learning", "facilitation-decision-frameworks"],
    link: "https://befriendingproject.wordpress.com/",
  },
  {
    id: "elabdco",
    name: "ELABD&CO",
    role: "Consultant",
    roleType: "Consultant network contributor",
    period: "Aug 2020-2021",
    status: "Past",
    cluster: "social-entrepreneurship-media-community",
    summary: "Collaborated in a consultant network focused on social innovation, impact assessment, hybrid enterprise, design, research, and facilitation.",
    evidenceFor: ["ecosystem-strategy", "facilitation-decision-frameworks"],
  },
  {
    id: "young-rubicam",
    name: "Young & Rubicam",
    role: "Planning",
    roleType: "Planning",
    period: "Aug 2015-Oct 2015",
    status: "Past",
    cluster: "social-entrepreneurship-media-community",
    summary: "Early professional experience in strategic planning and understanding audiences to build stronger narratives and connections.",
    evidenceFor: ["ecosystem-strategy"],
  },
];

const experienceGroups = [
  {
    id: "web3-governance-protocol-ecosystems",
    title: "Web3 Governance & Protocol Ecosystems",
    summary: "Protocol governance, DAO operations, delegation, proposal review, and ecosystem coordination.",
    items: ["optimism", "optimism-security-council-cohort-b", "scroll", "web3-governance-research"],
  },
  {
    id: "cooperative-organizational-design",
    title: "Cooperative & Organizational Design",
    summary: "Cooperative infrastructure, self-management, sociocracy, facilitation, and organizational learning.",
    items: ["matriz-experience", "alexsotodigital-practice", "ouitopia", "sociocracy-practica", "reimagina", "covive"],
  },
  {
    id: "social-entrepreneurship-media-community",
    title: "Social Entrepreneurship, Media & Community",
    summary: "Earlier work in social entrepreneurship, impact media, community building, venture support, and field learning.",
    items: ["disruptivo", "socialab", "caldero", "befriending-project", "elabdco", "young-rubicam"],
  },
];

const methods = [
  {
    id: "governance-reviews",
    title: "Governance Reviews",
    featured: true,
    summary: "Assess how decisions are proposed, discussed, approved, executed, and converted into organizational learning.",
    outputs: ["Governance map", "decision-flow diagnosis", "learning backlog"],
    relatedServices: ["governance-design", "dao-operations"],
    evidence: {
      projects: ["concordia"],
      experience: ["optimism", "scroll"],
      articles: ["value-based-compensation-daos"],
    },
  },
  {
    id: "coordination-diagnostics",
    title: "Coordination Diagnostics",
    featured: true,
    summary: "Identify repeated failure patterns across roles, incentives, rituals, handoffs, and accountability loops.",
    outputs: ["coordination map", "tension register", "learning-loop recommendations"],
    relatedServices: ["coordination-systems", "ecosystem-strategy"],
    evidence: {
      projects: ["matriz", "concordia"],
      experience: ["matriz-experience", "alexsotodigital-practice"],
      articles: ["mutualism-web3-era"],
    },
  },
  {
    id: "facilitation-decision-frameworks",
    title: "Facilitation & Decision Frameworks",
    featured: true,
    summary: "Design and facilitate conversations that make tensions explicit and translate disagreement into criteria, decisions, and next steps.",
    outputs: ["session design", "decision criteria", "decision records"],
    relatedServices: ["facilitation-conflict-resolution", "strategic-planning"],
    evidence: {
      projects: ["matriz"],
      experience: ["ouitopia", "alexsotodigital-practice"],
      articles: ["power-of-decentralization"],
    },
  },
  {
    id: "institutional-learning",
    title: "Institutional Learning",
    featured: false,
    summary: "Turn recurring tensions, retrospectives, and operational lessons into reusable institutional memory.",
    outputs: ["learning loops", "retrospective formats", "knowledge artifacts"],
    relatedServices: ["coordination-systems", "research-sprints"],
    evidence: {
      projects: ["matriz"],
      experience: ["matriz-experience", "ouitopia"],
      articles: ["development-without-destruction"],
    },
  },
];

const services = [
  {
    id: "governance-design",
    title: "Governance Design",
    problem: "Decision bottlenecks and governance confusion",
    outcome: "Clear governance structures, explicit decision rights, and better learning from decisions.",
    formats: ["Governance review", "workshop", "ongoing consulting"],
    evidence: {
      methods: ["governance-reviews", "facilitation-decision-frameworks"],
      projects: ["concordia"],
      experience: ["optimism", "scroll"],
      articles: ["value-based-compensation-daos", "power-of-decentralization"],
    },
  },
  {
    id: "coordination-systems",
    title: "Coordination Systems",
    problem: "Poor coordination across distributed teams",
    outcome: "Better operating rhythms, clearer roles, and explicit loops for learning from coordination failures.",
    formats: ["Coordination diagnostic", "research sprint", "fractional support"],
    evidence: {
      methods: ["coordination-diagnostics", "institutional-learning"],
      projects: ["matriz", "concordia"],
      experience: ["matriz-experience", "alexsotodigital-practice"],
      articles: ["mutualism-web3-era"],
    },
  },
  {
    id: "facilitation-conflict-resolution",
    title: "Facilitation & Conflict Resolution",
    problem: "Conflict, ambiguity, or stakeholder misalignment",
    outcome: "Productive friction, shared criteria, and decisions people can understand, execute, and revisit.",
    formats: ["Facilitation session", "organizational retreat", "strategy call"],
    evidence: {
      methods: ["facilitation-decision-frameworks"],
      projects: ["matriz"],
      experience: ["ouitopia", "alexsotodigital-practice"],
      articles: ["power-of-decentralization"],
    },
  },
  {
    id: "ecosystem-strategy",
    title: "Ecosystem Strategy",
    problem: "Ecosystem complexity and unclear incentives",
    outcome: "Better alignment between contributors, programs, incentives, governance processes, and learning feedback.",
    formats: ["Strategy call", "research sprint", "ongoing consulting"],
    evidence: {
      methods: ["coordination-diagnostics", "governance-reviews"],
      projects: ["concordia"],
      experience: ["optimism", "scroll"],
      articles: ["value-based-compensation-daos"],
    },
  },
  {
    id: "dao-operations",
    title: "DAO Operations Support",
    problem: "Scaling distributed governance and operations",
    outcome: "More reliable governance operations, clearer contribution paths, and better learning from proposal workflows.",
    formats: ["Fractional support", "research sprint", "ongoing consulting"],
    evidence: {
      methods: ["governance-reviews"],
      projects: ["concordia"],
      experience: ["optimism"],
      articles: ["value-based-compensation-daos"],
    },
  },
];

const projects = [
  {
    id: "matriz",
    title: "Matriz",
    type: "Cooperative",
    status: "Live",
    role: "Founder",
    featured: true,
    summary: "An ongoing laboratory for exploring cooperative governance, shared infrastructure, mutualist coordination, and collective learning among independent professionals.",
    problem: "Independent professionals often need shared infrastructure, collective accountability, and practical coordination systems without becoming a conventional firm.",
    approach: "Use the cooperative as a living context for testing contribution, reputation, shared resources, explicit governance, and learning from recurring coordination tensions.",
    lessons: ["Coordination systems need social legitimacy", "Governance must support real operating needs", "Projects are laboratories where practice evolves through reflection"],
    link: "https://matriz.coop/",
    evidence: {
      methods: ["coordination-diagnostics", "facilitation-decision-frameworks", "institutional-learning"],
      services: ["coordination-systems", "facilitation-conflict-resolution"],
      articles: ["mutualism-web3-era", "development-without-destruction"],
      experience: ["matriz-experience"],
    },
  },
  {
    id: "concordia",
    title: "Concordia",
    type: "Coordination tools",
    status: "In development",
    role: "Designer and builder",
    featured: true,
    summary: "An applied experiment in multi-group collaboration, governance context, shared decision processes, and reusable organizational memory.",
    problem: "Distributed groups need better ways to coordinate across teams, contexts, and decision spaces.",
    approach: "Use product design as a research context for explicit groups, roles, decision context, and reusable governance knowledge that can improve over time.",
    lessons: ["Coordination tooling should make context portable", "Governance knowledge needs structure before automation", "Adaptive organizations need memory they can reuse"],
    evidence: {
      methods: ["governance-reviews", "coordination-diagnostics"],
      services: ["governance-design", "coordination-systems", "ecosystem-strategy", "dao-operations"],
      articles: ["power-of-decentralization", "value-based-compensation-daos"],
      experience: ["alexsotodigital-practice"],
    },
  },
  {
    id: "inner-circles",
    title: "Inner Circles",
    type: "Coordination tool",
    status: "Prototype",
    role: "Contributor",
    featured: false,
    summary: "A peer-to-peer lending prototype exploring trust as collateral.",
    problem: "Trust-based lending is difficult to coordinate without legible relationships and accountability.",
    approach: "Experiment with social trust as a coordination primitive.",
    lessons: ["Social trust can become usable infrastructure when relationships are made explicit"],
    evidence: {
      methods: ["coordination-diagnostics"],
      services: ["coordination-systems"],
      articles: ["mutualism-web3-era"],
      experience: ["alexsotodigital-practice"],
    },
  },
  {
    id: "reggie",
    title: "Reggie",
    type: "AI agent",
    status: "In development",
    role: "UX feedback, tokenomics, beta testing",
    featured: false,
    summary: "An AI agent project exploring agent management, tokenomics, and user experience.",
    problem: "AI agents need coordination interfaces, accountability, and useful management models.",
    approach: "Support product feedback and token design exploration.",
    lessons: ["Agent systems still need explicit human governance and accountability"],
    evidence: {
      methods: ["coordination-diagnostics"],
      services: ["ecosystem-strategy"],
      articles: ["power-of-decentralization"],
      experience: ["alexsotodigital-practice"],
    },
  },
];

const articles = [
  {
    id: "minimum-viable-institution",
    title: "The Minimum Viable Institution",
    featured: true,
    currentPractice: true,
    theme: "Institutional Learning",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/the-minimum-viable-institution",
    summary: "A representative piece of the current practice: how organizations can create just enough shared structure to coordinate, learn, and adapt without becoming rigid.",
    evidenceFor: ["institutional-learning", "coordination-systems", "governance-design"],
  },
  {
    id: "power-of-decentralization",
    title: "The Power of Decentralization; and the Decentralization of Power",
    featured: true,
    theme: "Governance",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/the-power-of-decentralization%3B-and-the-decentralization-of-power?referrer=0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
    summary: "A reflection on decentralization as a political and organizational question: how power, legitimacy, and learning are distributed.",
    evidenceFor: ["governance-design", "facilitation-decision-frameworks"],
  },
  {
    id: "mutualism-web3-era",
    title: "Mutualism in the Web3 Era",
    featured: true,
    theme: "Mutualism",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/mutualism-in-the-web3-era?referrer=0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
    summary: "An exploration of mutualist economics, shared infrastructure, and cooperative learning in Web3 contexts.",
    evidenceFor: ["coordination-systems", "institutional-learning"],
  },
  {
    id: "value-based-compensation-daos",
    title: "Toward a Value-Based Compensation System for DAOs",
    featured: true,
    theme: "DAOs",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/toward-a-value-based-compensation-system-for-daos?referrer=0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
    summary: "A proposal-oriented article about contribution, compensation, value, accountability, and feedback in DAO systems.",
    evidenceFor: ["governance-design", "dao-operations", "ecosystem-strategy"],
  },
  {
    id: "development-without-destruction",
    title: "For Development Without Destruction",
    featured: true,
    theme: "Institutional Learning",
    source: "Paragraph",
    href: "https://paragraph.com/@alexsotodigital/for-development-without-destruction?referrer=0x3cd5fEC7FA9827cf0d262D6be5421A61CF615794",
    summary: "A piece on development, care, and the need for adaptive progress that does not destroy the systems it depends on.",
    evidenceFor: ["institutional-learning", "coordination-systems"],
  },
];

const faq = [
  {
    question: "What does Alex Soto do?",
    answer: "Alex Soto helps mission-driven organizations design governance and coordination systems that make decisions, tensions, and learning more explicit over time.",
  },
  {
    question: "Does Alex Soto work with DAOs?",
    answer: "Yes. Alex Soto works with DAOs, Web3 teams, ecosystem foundations, collectives, cooperatives, and distributed teams.",
  },
  {
    question: "Is this the official website of Alex Soto?",
    answer: "Yes. This is the official website of Alex Soto, also known as @alexsotodigital and alexsotodigital.eth.",
  },
  {
    question: "Does Alex Soto work remotely?",
    answer: "Yes. Alex works from Mexico / LATAM with remote-first organizations.",
  },
  {
    question: "Does Alex Soto work in English and Spanish?",
    answer: "Yes. Spanish is Alex's native language, and English is used at professional working proficiency.",
  },
  {
    question: "How can I hire Alex Soto?",
    answer: "The primary path is to book a strategy call through Calendly. You can also email a collaboration brief to explain the context, problem, and desired support.",
  },
  {
    question: "What methodologies does Alex Soto use?",
    answer: "Core methods include Governance Reviews, Coordination Diagnostics, Facilitation & Decision Frameworks, and Institutional Learning. These methods help organizations learn from decisions, tensions, and repeated coordination failures.",
  },
  {
    question: "Is Alex Soto a software engineer or crypto trader?",
    answer: "No. Alex's professional focus is governance, coordination, facilitation, institutional learning, and Web3 ecosystem work.",
  },
];

module.exports = {
  site,
  links,
  payments,
  experience,
  experienceGroups,
  methods,
  services,
  projects,
  articles,
  faq,
};
